### ISSUE TITLE
참조조문 참조판례 전처리 필요

### ISSUE THREAD

**Issue by Scureme-LEE** [sesac-NoF/NoF#28]
필요

**Comment by ykdb** [comment]
전처리 부분 참조 코드 

```
`# 불용어 파일을 읽어 불용어 목록 생성
with open(stopwords_file_path, 'r', encoding='utf-8') as f:
    stopwords = set(f.read().splitlines())

# 불용어 제거 함수 (리스트 상태로 처리)
def remove_stopwords(tokens):
    filtered_words = [
        word for word in tokens 
        if len(word) > 1 
        and word not in stopwords 
        and not word.isdigit()  # 숫자인 경우 제외
        and word not in stopwords_pick 
        and not re.match(pattern, word)
    ]
    return ' '.join(filtered_words)  # 문자열로 반환 / 리스트로 변환하지 말 것
```



```
# 전처리 함수 정의
def preprocess_content(content):
    if pd.isna(content):  # NaN 값에 대한 예외 처리
        return content
    
    # content가 문자열인지 확인
    if isinstance(content, str):
        content = content.replace('<br/>', '')
        content = content.replace('\n', '')
        content = content.replace('\r', '')
    
    return content

# applymap이 아닌 각 열에 개별적으로 apply 사용
for col in columns_to_preprocess:
    df_Labor[col] = df_Labor[col].apply(preprocess_content)
````

**Comment by ykdb** [comment]
> 법률 문서 문단에서 특정 문장들의 패턴을 찾아서 분류 후 같은 패턴의 문장 찾아서 결과 도출하는 방법

1. 텍스트 전처리
토큰화: 문단을 문장 단위 또는 단어 단위로 나누는 작업입니다.
불용어 제거: 의미 없는 단어(예: '그리고', '또한' 등)를 제거합니다.
형태소 분석: 각 단어의 품사를 식별합니다. 한국어의 경우 특히 유용합니다.

2. 패턴 정의
정규 표현식: 특정 키워드나 구조(예: "제N조" 또는 특정 법률 용어)로 패턴을 정의하고, 해당 표현식을 사용해 문장을 분류할 수 있습니다.
키워드 기반 패턴: 특정 키워드 리스트를 만들어, 해당 키워드가 포함된 문장을 분류합니다.
의미론적 패턴 분석: 법률 문장의 주제나 구조를 파악하기 위해 어휘 사전 또는 사전 훈련된 언어 모델(BERT 등)을 사용해 유사한 의미를 가지는 문장들을 그룹화합니다.

3. 문장 패턴 분류 및 유사도 분석
군집화 알고리즘: K-means, DBSCAN 등을 사용하여 문장의 패턴을 기준으로 유사한 문장들을 그룹화할 수 있습니다.
문장 임베딩: BERT, KoBERT 등의 사전 훈련된 모델을 사용하여 문장을 벡터로 변환한 후, 문장 간 유사도를 측정합니다.

4. 패턴 검색 및 결과 도출
유사도 측정: 코사인 유사도 등을 사용해 주어진 패턴과 유사한 문장을 찾아냅니다.
분석 결과 도출: 패턴이 일치하는 문장을 통계적으로 분석하거나, 요약해 결과를 도출합니다.

```
import re
import spacy
from transformers import pipeline

# NLP 모델 불러오기
nlp = spacy.load("ko_core_news_sm")
similarity_model = pipeline("feature-extraction", model="bert-base-multilingual-cased")

# 텍스트 데이터
text = """(여기에 법률 문단을 넣으세요)"""

# 정규 표현식 패턴을 정의하여 특정 문장 추출
pattern = r"(제\d+조).*"  # '제N조'로 시작하는 문장 찾기
matches = re.findall(pattern, text)

# 문장 임베딩을 통해 유사도 계산
def get_similarity(sentence1, sentence2):
    vec1 = similarity_model(sentence1)[0][0]
    vec2 = similarity_model(sentence2)[0][0]
    return cosine_similarity([vec1], [vec2])[0][0]

# 유사한 문장 찾기
for sentence in text.split("다. "):
    if get_similarity(target_sentence, sentence) > 0.85:
        print("유사한 문장:", sentence)

```

**Comment by ykdb** [comment]
> 유사하지 않은 문장은 새로운 패턴으로 인식

유사하지 않은 문장을 새로운 패턴으로 인식하려면 군집화 또는 분류를 활용하여 유사성 기준을 정하고, 유사하지 않은 문장은 별도의 그룹으로 배치하는 방식으로 접근할 수 있습니다. 아래는 이를 위한 구체적인 절차와 Python 코드 예시입니다.

1. 텍스트 전처리 및 임베딩
각 문장을 임베딩하여 고차원 벡터로 변환합니다.
BERT, SBERT 등의 모델을 사용하여 문장 간의 유사성을 비교할 수 있는 벡터를 생성합니다.
2. 군집화 적용
K-means, DBSCAN 등의 군집화 알고리즘을 사용하여 유사한 문장을 같은 군집으로 모읍니다.
DBSCAN을 사용할 경우, 유사하지 않은 문장은 '노이즈'로 분류되어 새로운 패턴으로 인식될 수 있습니다.
3. 새로운 패턴 인식
유사하지 않은 문장들은 별도의 군집에 할당되므로, 새로운 패턴으로 분류됩니다.
분류된 군집을 통해 기존 패턴과 새로운 패턴을 자동으로 구분합니다.


```

from sklearn.cluster import DBSCAN
from sklearn.metrics.pairwise import cosine_similarity
from transformers import pipeline
import numpy as np

# 임베딩 모델 로드
embedding_model = pipeline("feature-extraction", model="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")

# 텍스트 데이터
sentences = [
    "제1조 이 법은 ...",
    "제2조 이 법의 목적은 ...",
    # 여러 문장 추가
]

# 문장 임베딩 생성
embeddings = np.array([np.mean(embedding_model(sentence), axis=1) for sentence in sentences])

# DBSCAN으로 군집화
clustering = DBSCAN(eps=0.5, min_samples=2, metric="cosine").fit(embeddings)

# 결과 확인
for idx, label in enumerate(clustering.labels_):
    if label == -1:
        print(f"새로운 패턴으로 인식된 문장: {sentences[idx]}")
    else:
        print(f"기존 패턴 그룹 {label}에 속한 문장: {sentences[idx]}")

```

**Comment by ykdb** [comment]
> 패턴이 수십 개 이상으로 다양한 경우에는 몇 가지 효율적인 분석 방법을 적용할 수 있습니다. 법조항과 같은 텍스트에서 공통된 패턴을 식별하고 이를 활용하기 위해, 주로 클러스터링과 임베딩을 조합하는 접근이 효과적입니다.

1. 패턴 추출 및 전처리
수십 개 이상의 다양한 패턴을 미리 수작업으로 정의하거나 주석을 달면, 각 패턴 유형을 라벨로 설정하여 데이터셋을 구축합니다.
각 법조항이 포함하는 주요 키워드나 규칙(예: 제N조, 항, 호 등)을 기준으로 패턴을 정리하여, 특정 패턴에 매칭되는 공통 요소를 기반으로 분류할 수 있도록 전처리합니다.

2. 법조항 임베딩 생성
BERT, KoBERT, 또는 KoSentenceBERT 등 사전학습된 언어 모델을 사용하여 각 법조항을 벡터로 변환합니다. 벡터화하면 의미적으로 유사한 패턴들이 가까운 위치에 배치됩니다.
이 임베딩을 활용하여 유사한 법조항끼리 군집화할 수 있습니다. 특히 법조항의 패턴이 많을수록 이런 방식으로 구조를 파악하기 쉽습니다.

3. 유사도 기반 클러스터링
DBSCAN이나 KMeans와 같은 군집화 알고리즘을 사용하여 유사한 패턴끼리 그룹화합니다.
DBSCAN은 새로운 패턴이나 소수 패턴을 노이즈로 간주해 처리할 수 있고, KMeans는 미리 설정한 군집 수로 클러스터링해 패턴이 뚜렷하게 나뉠 경우 적합합니다.
각 클러스터가 특정 패턴의 법조항을 대표할 수 있도록 클러스터의 대표 문장을 추출할 수 있습니다.
클러스터링을 통해 대표적인 패턴만 남겨놓고 중복을 제거하면 분석 효율이 크게 향상됩니다.

4. 주요 패턴 추출 및 라벨링
군집화한 결과에서 대표 패턴을 추출하여, 각 패턴 그룹에 대해 규칙 기반으로 라벨을 지정하거나, 패턴의 의미적 내용을 요약하여 라벨링할 수 있습니다.
각 클러스터 내에서 가장 자주 등장하는 키워드, 문장 형식을 기반으로 패턴을 자동으로 라벨링하도록 스크립트를 작성할 수 있습니다. 예를 들어, "목적"을 포함하는 클러스터, "적용 범위"를 포함하는 클러스터 등으로 분류합니다.

5. 패턴 기반 모델 학습
전처리와 클러스터링을 통해 정의된 각 패턴 라벨을 학습 데이터의 타겟 레이블로 사용해 지도학습 모델을 훈련할 수 있습니다. 이를 통해, 새로운 법조항이 주어졌을 때 해당 법조항의 패턴 라벨을 자동으로 예측하게 할 수 있습니다.
이 모델은 SVM, 랜덤 포레스트, 또는 딥러닝 모델을 사용하여 패턴을 분류하도록 학습할 수 있으며, 성능이 충분하지 않을 경우에는 미세 조정을 통해 모델을 향상할 수 있습니다.

```
from sklearn.cluster import DBSCAN
from transformers import AutoTokenizer, AutoModel
import torch
import numpy as np
import pandas as pd

# KoSentenceBERT 모델 로드 (한국어 지원)
model_name = "jhgan/ko-sbert-sts"  # 한국어 문장 유사도 분석을 위한 KoSentenceBERT 모델
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

# 법조항 데이터 예시
sentences = [
    "제1조 이 법은 ...",
    "제2조 이 법의 목적은 ...",
    "제3조 적용 범위는 ...",
    # 추가 법률 문장들...
]

# 문장 임베딩 함수 정의
def get_embeddings(sentences):
    # 문장들을 토큰화하고 텐서 형태로 변환
    inputs = tokenizer(sentences, padding=True, truncation=True, return_tensors="pt")
    with torch.no_grad():
        model_output = model(**inputs)
    embeddings = model_output.last_hidden_state.mean(dim=1)  # 문장 임베딩 평균값 사용
    return embeddings.numpy()

# 문장 임베딩 생성
embeddings = get_embeddings(sentences)

# DBSCAN을 이용한 클러스터링 (eps와 min_samples는 데이터에 따라 조정)
clustering = DBSCAN(eps=0.5, min_samples=2, metric="cosine").fit(embeddings)

# 결과를 데이터프레임에 저장
df = pd.DataFrame({"문장": sentences, "클러스터 라벨": clustering.labels_})

# 클러스터별 대표 문장과 패턴 출력
for label in set(clustering.labels_):
    cluster_sentences = df[df["클러스터 라벨"] == label]["문장"].values
    if label == -1:
        print("\n새로운 패턴으로 인식된 문장들:")
    else:
        print(f"\n클러스터 {label}에 속한 문장들:")
    for sentence in cluster_sentences:
        print(f" - {sentence}")

# CSV 파일로 저장 (선택 사항)
df.to_csv("clustered_patterns.csv", index=False, encoding="utf-8-sig")
```

**Comment by ykdb** [comment]
클러스터가 3개로 무의미하게 분류됨

클러스터 20개로 임의로 지정하여 k-means로 다시 진행

**Comment by Scureme-LEE** [comment]
전처리 완료한 데이터를 보니까 민법, 민사소송법 등으로 붙여져야 하는데 법만 붙은 데이터가 존재함. 수정必

**Comment by Scureme-LEE** [comment]
> 전처리 완료한 데이터를 보니까 민법, 민사소송법 등으로 붙여져야 하는데 법만 붙은 데이터가 존재함. 수정必 [01.reference_preprocessing.ipynb](https://github.com/sesac-NoF/NoF/blob/28-%EC%B0%B8%EC%A1%B0%EC%A0%84%EC%B2%98%EB%A6%AC/01.reference_preprocessing.ipynb)

법 이름을 제대로 추출하니 기존 코드로도 해결이 됨.

**Comment by Scureme-LEE** [comment]
일부 (가)목, (다)항 이런식으로 되어있는 경우 빼고는 제대로 법 이름이 추출되었고 법 이름만 제대로 추출되면 해당 법 이름을 붙이는 단어가 아니므로 상관없다.

**Comment by Scureme-LEE** [comment]
4가지 분야에 대해 모두 코드를 돌려 sql에 입력함.

**Comment by Scureme-LEE** [comment]
결과값에서 조문을 참조시킬 예정인데 이를 위해 법이름과 조 이하의 내용을 / 로 분리해둠. 
조문간 분리는 ,를 기준으로 하였다. (괄호 바깥의 , 만이 split 기준점이다.)

**Comment by Scureme-LEE** [comment]
현행~참조 부문 처리와 공백인 부분이 있어 ,가 불필요하게 생긴거 제거해야한다.

**Comment by Scureme-LEE** [comment]
<br/> , [증명책임] 제거함

**Comment by Scureme-LEE** [comment]
현행~참조 부문을 가져와 앞의 것을 대체하니 법 이름까지도 지워버림

**Comment by Scureme-LEE** [comment]
~~[시행령시행령 -> (현행~) 안에 및이 들어가 있어서 previous_law를 조정하기]~~
