### ISSUE TITLE
판례 목록 조회

### ISSUE THREAD

**Issue by jungssg** [sesac-NoF/NoF#4]
국가법령정보 공동활용에서
판례 목록 조회 API 사용
[https://open.law.go.kr/LSO/openApi/guideResult.do](https://open.law.go.kr/LSO/openApi/guideResult.do)

**Comment by jungssg** [comment]
함수사용으로 lawService에서도 lawSearch의 df 사용가능하게

**Comment by ykdb** [comment]
판례내용 괄호 기호를 중심으로 수집
